(
  patch_it $SOURCE2 1

  OPTS="$OPTS --enable-gtk2 --disable-gnome --disable-artsc --with-static-prpls=gg,irc,jabber,msn,napster,novell,oscar,yahoo,zephyr --with-dynamic-prpls=gg,irc,jabber,msn,napster,novell,oscar,yahoo,zephyr --disable-gevolution"
  default_build

) > $C_FIFO 2>&1
