(
  export LDFLAGS="-Wl,-rpath,/opt/lunar/slang/lib" &&
  OPTS+=" --with-slang-library=/opt/lunar/slang/lib \
          --with-slang-includes=/opt/lunar/slang/include" &&

  default_build

) > $C_FIFO 2>&1
