#!/bin/bash
#   description: mount and umount the filesystem
#
# chkconfig: 345 15 89

if [ -e /etc/config.d/touchpad ]; then
   . /etc/config.d/touchpad
fi

start() {
    echo -n "Configuring Touchpad: " 
    tpconfig $ARGS > /dev/null 2>&1
    if [ $? ]; then
        echo -e $RESULT_OK
    else
        echo -e $RESULT_FAIL
    fi
}

stop() {
    exit 0;
}

# to avoid confusion we force only these options as being valid:
case "$1" in
  start|stop) ;;
           *) echo  "Usage: $0 {start|stop}"  ;;
esac

. /lib/lsb/init-functions

