#!/bin/bash
#
# ipsec    Starts, Stops and Reloads ipsec.
#
# chkconfig: 345 82 18
# description: strongswan is a secure VPN 
#              which rely on ipsec protocol
# processname: /usr/sbin/ipsec


start() {
	echo -n "Starting ipsec: "
	/usr/sbin/ipsec start
	echo -e $RESULT_OK || echo -e $RESULT_FAIL
}


stop() {
	echo -n "Stopping ipsec: "
	/usr/sbin/ipsec stop
	echo -e $RESULT_OK || echo -e $RESULT_FAIL
}


. /lib/lsb/init-functions
