prepare_install &&

install -dm755 /etc/fonts/conf.d &&
install -Dm644 font/PowerlineSymbols.otf      /usr/share/fonts/OTF/PowerlineSymbols.otf
install -Dm644 font/10-powerline-symbols.conf /etc/fonts/conf.avail/10-powerline-symbols.conf
ln -s ../conf.avail/10-powerline-symbols.conf /etc/fonts/conf.d/10-powerline-symbols.conf