OPTS+=" -D CMAKE_INSTALL_INCLUDEDIR=include/fltk1.3 \
        -D FLTK_BUILD_FLUID=OFF \
        -D FLTK_BUILD_TEST=OFF \
        -D FLTK_FLUID_EXECUTABLE=$MODULE \
        -D FLTK_LIBDIR=/usr/lib/fltk1.3 \
        -D OPTION_BUILD_SHARED_LIBS=ON \
        -W no-dev" &&

default_cmake_build
