#!/bin/bash
#
# irc     - the standard IRC daemon
#
# chkconfig: 345 80 20
# description: irc daemon
# processname: ircd
# config:      /etc/ircd.conf
# runas:       nobody

ARGS="-h `/bin/hostname`"

. /lib/lsb/init-functions

