(

  ./configure  --prefix=/usr        \
               --mandir=/usr/share  \
               --bindir=/usr/games  &&
  make                              &&
  prepare_install                   &&
  make    install

) > $C_FIFO 2>&1
