OPTS+=" --exec-prefix=/usr          \
        --datadir=/usr/share        \
        --sysconfdir=/etc           \
        --mandir=/usr/share/man     \
        --enable-mandatory-headers  \
        --with-init-dir=/etc/init.d \
        --with-rc-dir=/etc          \
        --enable-mandatory-headers  \
        --disable-ntsysv            \
        --with-xinetd-dir=/etc/xinetd.d"

OPTS+=" --sbindir=/usr/bin"

default_build
