(

   ./configure --prefix=/usr              \
               --bindir=/usr/bin          \
	       --sbindir=/usr/sbin        \
	       --datadir=/usr/share       \
	       --sysconfdir=/etc          \
	       --infodir=/usr/share/info  \
	       --mandir=/usr/share/man    \
	       --disable-xmltest         &&

    default_make

) > $C_FIFO 2>&1
