
OPTS+=" --without-xen \
        --with-udev \
        --without-hal \
        --disable-static \
        --without-netcf \
        --with-interface \
        --with-network \
        --with-secrets \
        --with-storage-lvm \
        --with-init-script=none"

default_build
