#!/bin/bash
#
# ConsoleKit: ConsoleKit daemon
#
# chkconfig: 345 90 10
# short: ConsoleKit
# description: The ConsoleKit maintains a list of sessions
# processname: console-kit-daemon
# pidfile: /var/run/ConsoleKit.pid

stop () {
  get_data

  echo -n "Stopping $SHORT: "
  if skill -SIGTERM $PROCESS; then
    echo -e $RESULT_OK
    rm -f $PIDFILE
  else
    echo -e $RESULT_FAILED
  fi
}

. /lib/lsb/init-functions

