#!/bin/bash
#
# ntp
# chkconfig: 345 31 69
# description: NTP is used to synchronize computer clocks
#  on a connected network or via GPS/phone/etc.
# processname: ntpd
# config: /etc/ntp.conf

ARGS="-g"
[ -f "/etc/ntp.conf" ] && ARGS="$ARGS -c /etc/ntp.conf"

reload () {
	# ntp is not reload-safe
	$0 restart
}

. /lib/lsb/init-functions

