CFLAGS="${CFLAGS/-fexceptions/}"
CXXFLAGS="${CXXFLAGS/-fexceptions/}"

OPTS+=" -Dtests=disabled \
        -Ddocs=disabled \
        -Dcpp_std=c++17 \
        -Dutilities=enabled \
        -Dbenchmark=disabled \
        -Dintrospection=enabled "

default_meson_build
