.TH "lmouse" "8" "0.0.1" "Chuck Mead" "Lunar mouse"
.SH "NAME"
.LP 
lmouse \- an interactive script to assist users and system administrators configure their mouse properly to work with gpm on Lunar Linux.
.SH "SYNTAX"
.LP 
lmouse
.br 

.SH "DESCRIPTION"
.LP 
lmouse is a shell script which interactively walks you through configuration of the console mouse under gpm.
.SH "OPTIONS"
.LP 
None
.SH "FILES"
.LP 
\fI/etc/config.d/mouse\fP 
.br 
\fI/etc/init.d/gpm\fP 
.SH "ENVIRONMENT VARIABLES"
.LP 
None
.SH "EXAMPLES"
.LP 
To run this program the standard way type:
.LP 
lmouse

.SH "AUTHORS"
.LP 
Chuck Mead <csm@moongroup.com>
.SH "SEE ALSO"
.LP 
gpm(8) gpm\-root(1) mev(1) mouse\-test(1) gpm\-types(7) 
