(

  OPTS+=" --libdir=/usr/lib/$MODULE --with-pkgconfigdir=/usr/lib/pkgconfig  \
          --includedir=/usr/include/$MODULE --sysconfdir=/etc/$MODULE --disable-static" &&

  ./autogen.sh &&

  default_build                                                                                                                               
                                                                                                                                              
) > $C_FIFO 2>&1
